### ISSUE TITLE
Slack keeps asking for notifications authorization

### ISSUE THREAD

**Issue by yann-soubeyrand** [sonnyp/Tangram#120]
Hi,

Each time I launch Tangram, Slack keeps asking me to enable notifications. I tried to click on the button “Don’t ask again on this computer”, and now Slack doesn’t ask me any more (which is expected), but the notifications are disabled and I have to enable them in the preferences each time I start Tangram. This problem doesn’t happen in GNOME Web.

**Tangram version**

Tangram version 1.3.1 installed via Flatpack.

**Linux distribution**

Fedora Silverblue 34.

**Flatpak version**

Flatpak 1.10.2

**Desktop environment**

GNOME 40.1.0 on Wayland.

**Comment by sonnyp** [comment]
I can't reproduce. Slack asked once only and notifications are working as expected.

I'm not sure what the problem is to be honest.

"Don’t ask again on this computer" sounds like you opt out of notifications so I'm not sure what you are expecting to happen.

If you can reproduce your problem with Tangram 1.4.0 please make and share a video.

**Comment by yann-soubeyrand** [comment]
Hi, the problem happened when I saved a tab with the `https://<workspace-name>.slack.com` URL, instead of the `https://app.slack.com/client/<XXXX>` URL. This issue can stay closed, thanks.
