### ISSUE TITLE
Toggle tab bar

### ISSUE THREAD

**Issue by airon90** [sonnyp/Tangram#61]
Is it possible to add a button to toggle the tab bar in order to maximise the window?

**Comment by sonnyp** [comment]
You mean for fullscreen? What is your use case?

**Comment by airon90** [comment]
No, I mean a button to toggle the bar containing the tabs. As of now, you cannot hide or show it from the position one choose in the menu and it steals space to the window

**Comment by sonnyp** [comment]
So you want to hide the tabs? 

If you're looking into having a single application then I recommend you use https://fedoramagazine.org/standalone-web-applications-gnome-web/

**Comment by sonnyp** [comment]
Note: Netflix and Spotify won't also work there

**Comment by airon90** [comment]
> If you're looking into having a single application

No, I want to use Tangram, I support it. I just want to say that tab bar could be hidden in order to maximise the space, then with the same button the bar could be shown again in order to change the webapp. Moreover, I use Firefox as my default browser and I'm fine with it

**Comment by sonnyp** [comment]
From a design perspective, it's not worth it.

* if we add a toggler button, every time the user wants to switch tab he/she will have to "show tabs" first, why ever hiding them then?
* one more button in the toolbar for which the function is not immediately obvious
* tabs moved to top or bottom don't take much space

**Comment by WouterBos** [comment]
I respect that you won't fix it but a way of hiding the tab bar would help in my use case. I want (and do) use Tangram on my television to be able to quickly switch between YouTube accounts of family members so we don't pollute each others profile and history.

If I want to see a video in full screen, I don't get fullscreen because the tab bar is in the way. Hiding the tab bar when I press F11 makes sense to me: this is what regular browsers do as well.

Other than that, love the philosophy of this browser!

**Comment by sonnyp** [comment]
The tab bar being visible in full-screen is a bug - feel free to create a new issue
