### ISSUE TITLE
Large icons for services (without text) (like Franz)

### ISSUE THREAD

**Issue by Pobega** [sonnyp/Tangram#73]
**Is your feature request related to a problem? Please describe.**
Currently in Tangram you are prompted to put text next to your service's icon to describe what it is. The result is that the sidebar is a bit wider than I'd like, and the service icons are very small.

**Describe the solution you'd like**
If there is no name for the service it'd be nice if the icons just became larger instead of remaining extremely tiny.

**Describe alternatives you've considered**
Living with the small icons, I guess.

**Additional context**
**Tangram**:
![Screenshot from 2019-12-26 14-21-00](https://user-images.githubusercontent.com/474525/71487753-056c4180-27eb-11ea-8821-b1503dce0b2c.png)
**Franz**:
![Screenshot from 2019-12-26 16-56-56](https://user-images.githubusercontent.com/474525/71491786-c648eb00-2800-11ea-860e-02f4198444ed.png)

**Comment by sonnyp** [comment]
I agree it would somehow look better (it's not a very GNOME-ish pattern though), in fact we had it like this at the beginning of the project but there are 2 issues

#### It doesn't work if you have the same website with multiple accounts

I guess it could be solved with customizing the icon / adding a label to it somehow. Any suggestion? Or maybe icon on top and label in the bottom instead of next to each others.

##### Not all website provide large app icons / favicons

An option could be to maintain a list of services/icons like we had at the very beginning of the project but it means shipping copyrighted brands/icons in the source code which I'm not super keen on. 

An other option would be to host that online and have Tangram fetch it. Not sure how users feel about that?

**Comment by Pobega** [comment]
> **It doesn't work if you have the same website with multiple accounts**

I think if the icons were larger you could do what you suggested - an icon on with an (optional) label on the bottom, yeah. That sounds reasonable to me.

> **Not all website provide large app icons / favicons**

Hm, this I don't have a solution for and it's a good point. Personally I'd rather have a large blurry icon than a small sharp icon but that obviously isn't the case for all users.

To your last point I don't mind where the icons are hosted, it's sort of irrelevant to me as a user. Though I imagine it'd be better to have less to maintain.

**Comment by giovannicaligaris** [comment]
I will also prefer larger icons than icons with text, it takes too much space on a small display. Also, I know I will sound a bit picky, but maybe including Libhandy would be a nice idea.

**Comment by tio-trom** [comment]
I'd love this too. And the ability to add custom icons.

**Comment by mediapinta** [comment]
WebApp Manager have a button that reach buttons online, but I don't know how it works (but it works).
