### ISSUE TITLE
Option to Temporarily Disable Tabs

### ISSUE THREAD

**Issue by Foggalong** [sonnyp/Tangram#78]
I use Tangram to host all the tabs for the chat services we use at work. Occasionally that also means contacting someone through Facebook messenger or once a month checking in on an email account.

It would be nice if it was possible to create tabs for these in Tangram with the option to then disable (and not load them), enabling them then for the duration they're needed for work. Similar features are in Rambox and Franz.

At the moment I just open these tabs in my browser but it'd be nice if I could have all my work communication happen through Tangram, rather than switching between the two. Using Tangram and just deleting the tabs when they're not in use isn't convenient since it means logging in from scratch each time.

**Comment by sonnyp** [comment]
My idea was rather to implement a feature in Tangram that allows you to create a new "virtual" application wich are basically separated tangram instances/windows with their own desktop name, desktop icon and tabs.

It was mostly done but I paused it to release version 1.0 quickly and because I ran into an issue on GNOME Shell but I don't think it's a blocker.

Would that work for you as well?

Would you be interested in working on that? I'm happy to help and provide pointers.

**Comment by Foggalong** [comment]
That would work great for me! Unfortunately I wouldn't be able to work on it; aside from town I know next to no Javascript unfortunately :sweat_smile:

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/21
