### ISSUE TITLE
Tangram opens authentication pop up window link in browser, breaking SSO

### ISSUE THREAD

**Issue by johannesgunnar** [sonnyp/Tangram#85]
While trying to sign in to my work's Rocket.chat instance which uses (keycloak) Tangram opens up the SSO Login in the default browser. Which breaks the login flow as Tangram never receives the authentication token.

An example, support for pop up windows, or some way to force links to open in Tangram might solve this.

I am on latest version on flathub
Fedora 32

**Comment by sonnyp** [comment]
Is it opening a new tab or a popup if you log in with a regular browser?

**Comment by sonnyp** [comment]
Request for comment https://github.com/sonnyp/Tangram/pull/104

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/91

**Comment by esijg** [comment]
Sorry about lack of comments after I first posted this. 

It looks like the updates since I first posted this have worked to a certain degree. It's acting a bit differently now, although not fully working.

It opens up the SSO link in the same Tangram window, but after logging in it gives me a white window that tells me it can be closed now. I am unable to advance from this point. Clicking the "Click Here" link does nothing. Changing the URL in the top bar fails to me logs me in. Pressing done just gives me that white page.

![Skjámynd frá 2022-03-19 21-05-01](https://user-images.githubusercontent.com/2924543/159138474-da01c2aa-6e01-4287-868b-05986f4c3289.png)
![Skjámynd frá 2022-03-19 21-05-28](https://user-images.githubusercontent.com/2924543/159138476-cecac1af-1f9d-4b34-951b-805d02d2bfb3.png)
![Skjámynd frá 2022-03-19 21-05-44](https://user-images.githubusercontent.com/2924543/159138477-8d0c355a-3f21-4135-b1ff-0ce86272db23.png)
